✨: Add github actions
digitalr00ts/fizzbuzz pull request #21
Opened 2020-11-08 08:46 UTC by pelmini

Resolves Issue #7

2020-11-09 19:40 UTC, CMeza99 requested changes

2020-11-09 19:44 UTC, CMeza99 commented
Should add `Closes #21` to git commit to automate closing (and linking) of the issue this PR addresses. Do you know how to do multi-line commits. Easiest way it to not do the commit message at the cli, and let git open vim.

see, https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

2020-11-12 06:51 UTC, pelmini commented on .github/workflows/tox_tests.yml
> +on: [push]
Would that be the server side of the CI stuff

2020-11-12 07:47 UTC, CMeza99 commented on .github/workflows/tox_tests.yml
> +on: [push]
yes. this is telling when Github should trigger. just need to append `pull_request` to the list.

2020-11-12 07:54 UTC, CMeza99 commented
If we want to have a cleaner commit history, I think having one commit and `Closes #21` going in the body of the commit. https://stackoverflow.com/a/42078093/2079786

I retract my comment about using vim for commit msg being easier. using two `-m` is easier. 😛  (see the Stack Overflow answer).

Think you can rebase and squash the commits? Rewriting history! lol

2020-11-12 07:57 UTC, CMeza99 commented
Wait. The PR is #21. The commit msg should be closing Issue #7. The PR will close when it is merged.

2020-11-12 19:42 UTC, pelmini commented
oops my bad. Thanks for catching that!

2020-12-25 00:27 UTC, closed without merging